### ISSUE TITLE
assert error: system_now >= self._system_now

### ISSUE THREAD

**Issue by tlk3** [bytewax/bytewax#479]
### Bug Description

Dataflow quits with asset error. 

### Python version (`python -V`)

3.11

### Bytewax version (pip list | grep bytewax)

0.20.1

### Operating System version (`uname -morp`)

Darwin 23.6.0 arm64 arm

### Relevant log output

```shell
Box<dyn Any>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.11/site-packages/bytewax/run.py", line 355, in <module>
    cli_main(**kwargs)
AssertionError: (src/operators.rs:823:65) error calling `StatefulBatchLogic.on_notify` in "dataflow_binance_trades.generic_window.stateful_batch" for key "1000FLOKIUSDT"
Caused by => AssertionError: 
Traceback (most recent call last):
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.11/site-packages/bytewax/operators/windowing.py", line 1152, in on_notify
    watermark = self.clock.on_notify()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.11/site-packages/bytewax/operators/windowing.py", line 288, in on_notify
    self.before_batch()
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.11/site-packages/bytewax/operators/windowing.py", line 254, in before_batch
    assert system_now >= self._system_now
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Steps to Reproduce

Not sure. Happens randomly with a dataflow that had been working fine for quite some time, as far as I know.

**Comment by tlk3** [comment]
```
flow = Dataflow('dataflow_binance_trades')

clock_config = EventClock(
    lambda data: datetime.fromtimestamp(data['T'] / 1000, tz=timezone.utc),
    wait_for_system_duration=timedelta(seconds=1)
)
align_to = datetime(2023, 1, 1, tzinfo=timezone.utc)
window_config = TumblingWindower(align_to=align_to, length=timedelta(seconds=1),)

s = (
    op.input('kafka_source', flow, kafka_source)
    .then(op.map, 'deserialize', deserialize)
    .then(fold_window, 'window', clock_config, window_config, list, accumulate, list.__add__)
)


X = TypeVar("X")


def rekey_by_window(key_id_obj: Tuple[str, Tuple[int, X]]) -> Tuple[str, X]:
    key, id_obj = key_id_obj
    win_id, obj = id_obj
    return f"{key}-{win_id}", obj


keyed_metadata = op.map("rekey_meta", s.meta, rekey_by_window)
keyed_stream = op.map("rekey_stream", s.down, rekey_by_window)
joined_stream = op.join("check_joined", keyed_metadata, keyed_stream)


def unkey_join_rows(rekey_row: Tuple[str, Tuple[WindowMetadata, list]]) -> Tuple[str, Tuple[WindowMetadata, list]]:
    rekey, row = rekey_row
    key, _win_id = rekey.rsplit("-", maxsplit=1)
    return key, row


cleaned_joined_stream = op.map("unkey_joined", joined_stream, unkey_join_rows)

s = op.map('agg', cleaned_joined_stream, bars.to_ohlc)
s = op.map('downsample', s, downsample)
s = op.filter('filter_null', s, lambda data: data[1] != {})

```

**Comment by tlk3** [comment]
cleaned_joined_stream looks like this:

```
('BOMEUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(0.007598, 345.982528), (0.007597, 504.577546)]))
('SUIUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(0.6805, 62.81015), (0.6805, 1.6332)]))
('ATOMUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(6.032, 26.359840000000002), (6.032, 73.95232)]))
('DOGEUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(0.11121, 63.278490000000005), (0.11121, 1226.7575100000001), (0.11121, 829.40418)]))
('BNBUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(519.69, 3440.3478000000005), (519.68, 446.92479999999995), (519.62, 5.1962), (519.61, 233.8245), (519.62, 1106.7906)]))
('BNXUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(1.1475, 1402.4745), (1.1474, 233.72537999999997), (1.1473, 504.12361999999996), (1.1472, 313.30032), (1.1471, 172.17971), (1.147, 1010.0482000000001), (1.1469, 351.29547)]))
('MASKUSDT', (WindowMetadata(open_time=datetime.datetime(2024, 7, 7, 0, 59, 59, tzinfo=datetime.timezone.utc), close_time=datetime.datetime(2024, 7, 7, 1, 0, tzinfo=datetime.timezone.utc), merged_ids=set()), [(2.119, 2.119)]))

```

Then there are some aggregations, creating a dict of data, filtering null values, and output to StdOutSink.

**Comment by Psykopear** [comment]
Yes, it does seem to be caused by a non monotonic clock. It's interesting to note that the issues seems to appear frequently only on MacOS, and given we are using UTC datetimes, it shouldn't be caused by daylight savings times switches or even negative leap seconds, so your hunch about the system clock that is resynced seems reasonable, even though it's hard to know for sure if we can't reproduce the problem. As you said, using `time.monotonic_ns` would mean we still need a "starting time" in system time to be able to compare, so it could make the issue less frequent but would hardly solve the problem.
I'm not sure we have a way to guarantee that that assert never fails if we work with system time. How bad would it be to instead "wait" for the system time to catch up (so not update `self._system_now` until `now_getter() > self._system_now`) and spit an error log in that case? Maybe capping the difference to a small tolerance, so that if the time goes back by an hour the dataflow still crashes, but if it's a matter of a few milliseconds we log loudly and move on.
