### ISSUE TITLE
Installing Bytewax for Python 3.8.9 on MacOS Fails

### ISSUE THREAD

**Issue by awmatheson** [bytewax/bytewax#49]
### Bug Description

When installing Bytewax for Python 3.8.9 on MacOS, pip tries to build Bytewax and then requires Maturin and Rust. This is an older 9.8 version, but is still used. When I tried to simulate this in a docker container I couldn't replicate the behavior. I could also not replicate the behavior with Conda, since Conda skips 3.8.9.  

### Python version (`python -V`)

Python 3.8.9

### Bytewax version (pip list | grep bytewax)

bytewax 0.8.0

### Relevant log output

```shell
Collecting bytewax
  Downloading bytewax-0.8.0.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 4.0 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/bin/python3.8 /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-bll3g_fv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12,<0.13'
       cwd: None
  Complete output (59 lines):
  Collecting maturin<0.13,>=0.12
    Downloading maturin-0.12.11.tar.gz (141 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting tomli>=1.1.0; python_version < "3.11"
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/bin/python3.8 /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/tmppmkzoa2r
         cwd: /private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-install-mzpj84mt/maturin
    Complete output (36 lines):
    running bdist_wheel
    running build
    installing to build/bdist.macosx-12.1-x86_64/wheel
    running install
    Traceback (most recent call last):
      File "/Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-etccmpel/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-etccmpel/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-etccmpel/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 118, in <module>
        setup(
      File "/private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-etccmpel/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/awmatheson/.pyenv/versions/3.8.9/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/awmatheson/.pyenv/versions/3.8.9/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/awmatheson/.pyenv/versions/3.8.9/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-etccmpel/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/Users/awmatheson/.pyenv/versions/3.8.9/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/awmatheson/.pyenv/versions/3.8.9/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 60, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
  You should consider upgrading via the '/Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/bin/python3.8 -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/bin/python3.8 /Users/awmatheson/.pyenv/versions/3.8.9/envs/py389/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lx/0qxsj_495jl6_8vg_0wpj24h0000gn/T/pip-build-env-bll3g_fv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12,<0.13' Check the logs for full command output.
```

### Steps to Reproduce

1. `brew install pyenv pyenv-virtualenv`
2. `eval "$(pyenv init --path)"`
3. `eval "$(pyenv init -)"`
4. `pyenv install 3.8.9`
5.  `pyenv virtualenv 3.8.9 py389`
6.  `pyenv local py389`
7.  `pyenv activate py389`

**Comment by awmatheson** [comment]
The current workaround is to install Rust and Maturin and then the build will work.
