### ISSUE TITLE
Issue using KafkaInputConfig with spawn_cluster

### ISSUE THREAD

**Issue by awmatheson** [bytewax/bytewax#94]
### Bug Description

When running the dataflow in [this repo](https://github.com/bytewax/real-time-data-enrichment-with-bytewax) that uses the `KafkaInputConfig` the dataflow works correctly while using `cluster_main`, but when substituting `cluster_main` with `spawn_cluster` the dataflow fails with the error shown in the log output below.

### Python version (`python -V`)

Python 3.9

### Bytewax version (pip list | grep bytewax)

bytewax 0.10.0

### Relevant log output

```shell
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/pool.py", line 114, in worker
    task = get()
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/queues.py", line 371, in get
    return _ForkingPickler.loads(res)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/dill/_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
TypeError: argument 'auto_commit': 'int' object cannot be converted to 'PyBool'
^CProcess SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/awmatheson/bytewax/real-time-data-enrichment-with-bytewax/src/dataflow.py", line 55, in <module>
    spawn_cluster(flow, input_config, output_builder)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/bytewax/execution.py", line 168, in spawn_cluster
    future.get()
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/pool.py", line 765, in get
    self.wait(timeout)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/site-packages/multiprocess/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/awmatheson/anaconda3/envs/bytewax39/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Steps to Reproduce

Follow the steps in the README.md and run the dataflow with `spawn_cluster` instead of `cluster_main`

**Comment by davidselassie** [comment]
I think this was a typo in the code to generate the arguments for pickling this config. I think I accidentally fixed this here https://github.com/bytewax/bytewax/pull/96/files#diff-e07f5e087e8f4def9cde86154f738e548f4b411669b2fdca88b7fca51d538b8bL194

**Comment by awmatheson** [comment]
fixed in picklebug
